import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import seed from "../../data/watches.seed.json";
import { searchSeedWatches, seedWatches } from "./seed";
import { compactReference } from "./watchIdentity";
import { groupWatchesForDisplay } from "./watchGroups";

interface SeedSource {
  sourceUrl: string;
}

const seedSql = readFileSync(new URL("../../data/seed.sql", import.meta.url), "utf8");
const seedSqlLines = seedSql.split("\n");
const seedWatchRowsById = new Map<number, string>();
const seedSourceSelects = new Set<string>();

for (const line of seedSqlLines) {
  const watchRow = line.match(/^\((\d+),/);
  if (watchRow) seedWatchRowsById.set(Number(watchRow[1]), line);
  if (line.startsWith("SELECT ")) seedSourceSelects.add(line);
}

function metricKey(value: number | null | undefined): string {
  return value == null ? "null" : Number(value).toFixed(2);
}

function normalizedBrandIdentity(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLowerCase()
    .replace(/&/gu, " and ")
    .replace(/\b(?:watches?|company|co)\b/gu, " ")
    .replace(/[^a-z0-9]+/gu, "")
    .trim();
}

function repeatedModelPhrase(value: string): string | null {
  const tokens = value
    .toLowerCase()
    .replace(/[^a-z0-9.]+/gu, " ")
    .trim()
    .split(/\s+/u)
    .filter(Boolean);

  for (let size = 6; size >= 2; size -= 1) {
    for (let start = 0; start + size * 2 <= tokens.length; start += 1) {
      const phrase = tokens.slice(start, start + size).join(" ");
      for (let compare = start + size; compare + size <= tokens.length; compare += 1) {
        if (phrase === tokens.slice(compare, compare + size).join(" ")) return phrase;
      }
    }
  }

  return null;
}

function sqlValue(value: unknown): string {
  if (value == null) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

describe("watch seed data integrity", () => {
  it("uses unique IDs", () => {
    const ids = seed.map((watch) => watch.id);

    expect(new Set(ids).size).toBe(ids.length);
  });

  it("does not repeat the same brand, model, reference, and case size", () => {
    const keys = seed.map((watch) =>
      [watch.brand, watch.model, watch.reference, watch.caseMm]
        .map((value) => String(value).trim().toLowerCase())
        .join("|")
    );

    expect(new Set(keys).size).toBe(keys.length);
  });

  it("does not repeat the same compact reference and full dimensions", () => {
    const seen = new Map<string, number>();
    const duplicates: string[] = [];

    for (const watch of seed) {
      const key = [
        compactReference(watch.reference),
        metricKey(watch.lugToLugMm),
        metricKey(watch.caseMm),
        metricKey(watch.thicknessMm),
        metricKey(watch.lugWidthMm)
      ].join("|");
      const duplicateId = seen.get(key);
      if (duplicateId) duplicates.push(`${duplicateId}/${watch.id}:${key}`);
      seen.set(key, watch.id);
    }

    expect(duplicates).toEqual([]);
  });

  it("does not repeat product numbers through brand spelling aliases", () => {
    const seen = new Map<string, number>();
    const duplicates: string[] = [];

    for (const watch of seed) {
      const reference = compactReference(watch.reference);
      if (reference.length < 3 || !/\d/u.test(reference)) continue;
      const key = `${normalizedBrandIdentity(watch.brand)}|${reference}`;
      const duplicateId = seen.get(key);
      if (duplicateId) duplicates.push(`${duplicateId}/${watch.id}:${key}`);
      seen.set(key, watch.id);
    }

    expect(duplicates).toEqual([]);
  });

  it("keeps the D1 seed SQL generated from the JSON seed data", () => {
    expect(seedSql).toContain("-- Generated by npm run data:seed-sql. Do not edit by hand.");

    for (const watch of seed) {
      expect(seedWatchRowsById.get(watch.id)).toContain(
        `(${watch.id}, ${sqlValue(watch.brand)}, ${sqlValue(watch.model)}`
      );

      for (const source of watch.sources) {
        expect(
          seedSourceSelects.has(
            `SELECT ${watch.id}, ${sqlValue(source.sourceUrl)}, ${sqlValue(source.note ?? null)}`
          )
        ).toBe(true);
      }
    }
  });

  it("requires a positive lug-to-lug value and at least one valid source URL", () => {
    for (const watch of seed) {
      expect(watch).not.toHaveProperty(["confi", "dence"].join(""));
      expect(watch.lugToLugMm).toBeGreaterThan(0);
      expect(watch.sources.length).toBeGreaterThan(0);

      for (const source of watch.sources) {
        expect(() => new URL(source.sourceUrl)).not.toThrow();
      }
    }
  });

  it("keeps display and grouping metadata clean", () => {
    const htmlEntityPattern = /&(?:amp|quot|apos|lt|gt|#\d+|#x[\da-f]+);/iu;
    const editorialHeadlinePattern =
      /^(?:introducing|hands[ -]on|a closer look|new release)\b|\b(?:as reviewed|reviewed (?:generation|example)|weekly watch photo|in conversation with|everything you need to know)\b/iu;

    for (const watch of seed) {
      const record = watch as Record<string, unknown>;
      for (const field of ["brand", "model", "reference", "canonicalModel", "modelGroup", "variant"]) {
        const value = record[field];
        if (value == null) continue;
        expect(value, `${watch.id}:${field}`).toBeTypeOf("string");
        expect(String(value), `${watch.id}:${field}`).toBe(String(value).trim());
        expect(String(value), `${watch.id}:${field}`).not.toMatch(htmlEntityPattern);
      }

      expect(Boolean(record.canonicalModel), `${watch.id}:canonicalModel/modelGroup`).toBe(Boolean(record.modelGroup));
      if (record.variant) {
        expect(record.canonicalModel, `${watch.id}:variant canonicalModel`).toBeTruthy();
        expect(record.modelGroup, `${watch.id}:variant modelGroup`).toBeTruthy();
      }

      expect(watch.model.length, `${watch.id}:model length`).toBeLessThanOrEqual(90);
      expect(watch.reference.length, `${watch.id}:reference length`).toBeLessThanOrEqual(90);
      expect(watch.model, `${watch.id}:model editorial headline`).not.toMatch(editorialHeadlinePattern);
      expect(watch.reference, `${watch.id}:reference editorial headline`).not.toMatch(editorialHeadlinePattern);
      if (watch.id !== 7026) {
        expect(repeatedModelPhrase(watch.model), `${watch.id}:repeated model phrase`).toBeNull();
      }
    }
  });

  it("includes the planned Patek Philippe and Citizen expansion references without duplicates", () => {
    const referencesByBrand = (brand: string) =>
      seed.filter((watch) => watch.brand === brand).map((watch) => watch.reference);

    const patekReferences = referencesByBrand("Patek Philippe");
    const citizenReferences = referencesByBrand("Citizen");

    expect(patekReferences.length).toBeGreaterThanOrEqual(21);
    expect(new Set(patekReferences).size).toBe(patekReferences.length);
    expect(patekReferences).toEqual(
      expect.arrayContaining(["5811/1G-001", "5712/1A-001", "5167A-001", "5168G-010", "5821/1A-001"])
    );

    expect(citizenReferences.length).toBeGreaterThanOrEqual(27);
    expect(new Set(citizenReferences).size).toBe(citizenReferences.length);
    expect(citizenReferences).toEqual(
      expect.arrayContaining(["NB6021-17E", "NJ0180-80X", "NB6050-51W", "NJ0150-81L", "NJ0150-81Z"])
    );
  });

  it("includes the Grand Seiko expansion references without duplicates", () => {
    const grandSeikoReferences = seed.filter((watch) => watch.brand === "Grand Seiko").map((watch) => watch.reference);

    expect(grandSeikoReferences.length).toBeGreaterThanOrEqual(99);
    expect(new Set(grandSeikoReferences).size).toBe(grandSeikoReferences.length);
    expect(grandSeikoReferences).toEqual(
      expect.arrayContaining(["SBGN027", "SBGE285", "SBGW283", "SBGY013", "SLGB005", "SBGH376", "SBGX355"])
    );
  });

  it("includes the full official DOXA lug-to-lug import", () => {
    const officialDoxaRecords = seed.filter(
      (watch) =>
        watch.brand === "Doxa" &&
        watch.sources.some((source: SeedSource) => source.sourceUrl.startsWith("https://doxawatches.com/products/"))
    );
    const officialDoxaPages = new Set(
      officialDoxaRecords.flatMap((watch) =>
        watch.sources
          .filter((source: SeedSource) => source.sourceUrl.startsWith("https://doxawatches.com/products/"))
          .map((source: SeedSource) => source.sourceUrl)
      )
    );

    expect(officialDoxaRecords).toHaveLength(291);
    expect(officialDoxaPages.size).toBe(120);
    expect(officialDoxaRecords.map((watch) => watch.reference)).toEqual(
      expect.arrayContaining([
        "795.10.101.10",
        "804.10.351.10",
        "823.50.121.20-SE14",
        "840.80.031.15",
        "862.10.351.10"
      ])
    );
    expect(officialDoxaRecords.find((watch) => watch.reference === "840.80.031.15")).toMatchObject({
      lugToLugMm: 44.5,
      caseMm: 42.5,
      thicknessMm: 13.65,
      lugWidthMm: 20
    });
    expect(officialDoxaRecords.find((watch) => watch.reference === "862.10.351.10")).toMatchObject({
      lugToLugMm: 47.6,
      caseMm: 40,
      thicknessMm: 14.15,
      lugWidthMm: 20
    });
  });

  it("includes the full official Union Glashütte catalog import", () => {
    const officialUnionRecords = seed.filter(
      (watch) =>
        watch.brand === "Union Glashütte" &&
        watch.sources.some((source: SeedSource) =>
          /^https:\/\/www\.union-glashuette\.com\/en_int\/d\d+\.html$/u.test(source.sourceUrl)
        )
    );
    const officialUnionPages = new Set(
      officialUnionRecords.flatMap((watch) =>
        watch.sources
          .filter((source: SeedSource) =>
            /^https:\/\/www\.union-glashuette\.com\/en_int\/d\d+\.html$/u.test(source.sourceUrl)
          )
          .map((source: SeedSource) => source.sourceUrl)
      )
    );

    expect(officialUnionRecords).toHaveLength(72);
    expect(officialUnionPages.size).toBe(72);
    expect(new Set(officialUnionRecords.map((watch) => compactReference(watch.reference))).size).toBe(72);
    expect(officialUnionRecords.map((watch) => watch.reference)).toEqual(
      expect.arrayContaining([
        "D015.527.17.011.09",
        "D007.458.16.039.00",
        "D014.927.11.057.00",
        "D017.407.11.091.00"
      ])
    );
    expect(officialUnionRecords.find((watch) => watch.reference === "D015.527.17.011.09")).toMatchObject({
      lugToLugMm: 49.47,
      caseMm: 41,
      thicknessMm: 15.5,
      lugWidthMm: 22
    });
    expect(officialUnionRecords.find((watch) => watch.reference === "D013.207.17.026.00")).toMatchObject({
      lugToLugMm: 39.39,
      caseMm: 33,
      thicknessMm: null,
      lugWidthMm: 16
    });
  });

  it("includes the full-site MONOCHROME lug-to-lug audit import", () => {
    const monochromeRecords = seed.filter((watch) =>
      watch.sources.some((source: SeedSource) => source.sourceUrl.startsWith("https://monochrome-watches.com/"))
    );
    const monochromeSources = monochromeRecords.flatMap((watch) =>
      watch.sources.filter((source: SeedSource) => source.sourceUrl.startsWith("https://monochrome-watches.com/"))
    );
    const monochromePages = new Set(monochromeSources.map((source) => source.sourceUrl));

    expect(monochromeRecords.length).toBeGreaterThanOrEqual(1_617);
    expect(monochromeSources.length).toBeGreaterThanOrEqual(2_246);
    expect(monochromePages.size).toBeGreaterThanOrEqual(1_389);
    expect(monochromeRecords.map((watch) => watch.reference)).toEqual(
      expect.arrayContaining(["5200G", "SBGW289", "UR-100V", "HU-01"])
    );
    expect(monochromeRecords.find((watch) => watch.reference === "SBGW289")).toMatchObject({
      lugToLugMm: 42.7,
      caseMm: 36.5
    });
  });

  it("keeps confirmed duplicate imports retired and their sources reassigned", () => {
    const retiredDuplicateIds = [
      1359, 2614, 2648, 2666, 2712, 2725, 2754, 2797, 2805, 2814, 2869, 2889, 2929, 2931,
      2976, 3025, 3032, 3067, 3068, 3110, 4022, 4023, 4026, 4030, 4031, 4032, 4033, 4035, 4036,
      4037, 4040, 4041, 4042, 4043, 4044, 4045, 4046, 4048, 4049, 4052, 4053, 4054, 4056,
      4057, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4069, 4070, 4071, 4072,
      4073, 4074, 4075, 4218, 4221, 4252, 4265, 5079, 6139, 6312, 6482, 6984, 6994, 7025,
      7035, 7036, 7042, 7090, 7091, 7093, 7112, 7122, 7135, 7139, 7141, 7151, 7165, 7167,
      7169, 7175, 7184, 7185, 7227, 7228, 7232, 7234, 7245, 7248, 7266, 7267, 7269, 7280,
      7302, 7332, 7336, 7338, 7339, 7353, 7365, 7369, 7371, 7372, 7389, 7404, 7427, 7430,
      7435, 7445, 7446, 7447, 7448, 7450, 7479
    ];
    const seedIds = new Set(seed.map((watch) => watch.id));

    expect(retiredDuplicateIds.filter((id) => seedIds.has(id))).toEqual([]);
    expect(seed.find((watch) => watch.id === 347)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl: "https://monochrome-watches.com/omega-speedmaster-silver-snoopy-award-50th-anniversary-review-price/"
        })
      ])
    );
    expect(seed.find((watch) => watch.id === 6694)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl: "https://monochrome-watches.com/konstantin-chaykin-takes-on-the-silver-screen/"
        })
      ])
    );
    expect(seed.find((watch) => watch.id === 7396)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl:
            "https://monochrome-watches.com/introducing-gerald-charles-genta-maestro-9-0-roman-tourbillon-hand-hammered-dial-vaucher-specs-price/"
        })
      ])
    );
    expect(seed.find((watch) => watch.id === 4309)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl:
            "https://www.ablogtowatch.com/new-release-grand-seiko-sbgj275-and-sbgm253-caliber-9s-25th-anniversary-limited-edition-gmt-watches/"
        })
      ])
    );
    expect(seed.find((watch) => watch.id === 6467)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl:
            "https://www.ablogtowatch.com/new-release-tag-heuer-monaco-flyback-chronograph-and-carrera-chronograph-tourbillon-extreme-sport-th-carbonspring-watches/"
        })
      ])
    );
    expect(seed.find((watch) => watch.id === 1424)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl: "https://monochrome-watches.com/2020-doxa-sub-300-cosc-collection-6-colours-hands-on-price/"
        })
      ])
    );
    expect(seed.find((watch) => watch.id === 1771)?.sources).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sourceUrl:
            "https://www.ablogtowatch.com/hands-on-debut-christopher-ward-brings-back-the-jj01-with-the-c1-jump-hour-mk-v/"
        })
      ])
    );
  });

  it("returns planned expansion records through seed search", () => {
    for (const query of ["5712", "5167", "Promaster", "TSUYOSA", "Series8", "SBGN027", "SLGB005", "SBGX355"]) {
      expect(searchSeedWatches(query).length).toBeGreaterThan(0);
    }
  });

  it("returns Worn & Wound batch records through seed search", () => {
    for (const query of ["Deep Space Blue", "Crossroads S 36", "Inflection", "DW-5600MNC", "JetFlyer", "Grand Tonneau"]) {
      expect(searchSeedWatches(query).length).toBeGreaterThan(0);
    }
  });

  it("returns AV86 records through current, historical, and regional brand names", () => {
    const av86Records = seed.filter((watch) => watch.brand === "AV86");

    expect(av86Records).toHaveLength(41);
    for (const query of ["AV86", "About Vintage", "Skov Andersen"]) {
      expect(searchSeedWatches(query).filter((watch) => watch.brand === "AV86")).toHaveLength(41);
    }
    expect(seedSql).toContain("av86 about vintage skov andersen");
  });

  it("groups normalized variant-only seed families for display", () => {
    const expectedGroups = [
      ["omega-seamaster-diver-300m-42mm", [6, 7]],
      ["omega-speedmaster-moonwatch-professional-42mm", [2]],
      ["formex-reef-39-5mm-automatic-cosc-300m", [7]],
      ["traska-commuter-36", [3]],
      ["zelos-hammerhead-43-field", [7]],
      ["mido-multifort-tv-big-date-40mm", [4]],
      ["grand-seiko-sport-quartz-gmt-39mm", [2]],
      ["grand-seiko-elegance-manual-winding-37-3mm", [5]],
      ["grand-seiko-hand-winding-spring-drive-38-5mm", [4]],
      ["grand-seiko-evolution-9-spring-drive-5-days-40mm", [4]],
      ["grand-seiko-spring-drive-u-f-a-37mm", [4]],
      ["grand-seiko-62gs-mechanical-hi-beat-36000-38mm", [4]],
      ["fears-brunswick-40-5-jump-hour", [6]],
      ["mido-multifort-tv-big-date", [2, 6]],
      ["sternglas-naos-automatic-38mm-black", [2]],
      ["sternglas-naos-automatic-38mm-blue", [2]],
      ["sternglas-naos-automatic-38mm-white", [4]],
      ["breitling-chronomat-b01-42-nfl", [26]],
      ["swatch-moonswatch", [21]],
      ["christopher-ward-bel-canto-c1", [21]],
      ["seiko-5-sports", [20]],
      ["mido-ocean-star-tribute", [2]],
      ["zenith-chronomaster-sport", [6]],
      ["bianchet-b-1-618-ultrafino", [1, 8]],
      ["bianchet-b-1-618-flying-tourbillon-sport-gmt", [7]],
      ["bianchet-b-1-618-flying-tourbillon-grande-date", [12]],
      ["glash-tte-original-seventies-chronograph-panorama-date", [6]],
      ["studio-underd0g-x-time-tide-01series-gen-3", [2]],
      ["tag-heuer-formula-1-chronograph", [4]],
      ["tag-heuer-carrera-chronograph-tourbillon-extreme-sport", [3]]
    ] as const;

    for (const [modelGroup, variantCounts] of expectedGroups) {
      const groups = groupWatchesForDisplay(seedWatches.filter((watch) => watch.modelGroup === modelGroup));
      const actualVariantCounts = groups.map((group) => group.variantCount).sort((a, b) => a - b);
      const expectedVariantCounts = [...variantCounts].sort((a, b) => a - b);

      expect(actualVariantCounts, modelGroup).toEqual(expectedVariantCounts);
    }
  });
});
