import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import seed from "../../data/watches.seed.json";
import { searchSeedWatches, seedWatches } from "./seed";
import { compactReference } from "./watchIdentity";
import { groupWatchesForDisplay } from "./watchGroups";

const seedSql = readFileSync(new URL("../../data/seed.sql", import.meta.url), "utf8");

function metricKey(value: number | null | undefined): string {
  return value == null ? "null" : Number(value).toFixed(2);
}

function sqlValue(value: unknown): string {
  if (value == null) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

describe("watch seed data integrity", () => {
  it("uses unique IDs", () => {
    const ids = seed.map((watch) => watch.id);

    expect(new Set(ids).size).toBe(ids.length);
  });

  it("does not repeat the same brand, model, reference, and case size", () => {
    const keys = seed.map((watch) =>
      [watch.brand, watch.model, watch.reference, watch.caseMm]
        .map((value) => String(value).trim().toLowerCase())
        .join("|")
    );

    expect(new Set(keys).size).toBe(keys.length);
  });

  it("does not repeat the same compact reference and full dimensions", () => {
    const seen = new Map<string, number>();
    const duplicates: string[] = [];

    for (const watch of seed) {
      const key = [
        compactReference(watch.reference),
        metricKey(watch.lugToLugMm),
        metricKey(watch.caseMm),
        metricKey(watch.thicknessMm),
        metricKey(watch.lugWidthMm)
      ].join("|");
      const duplicateId = seen.get(key);
      if (duplicateId) duplicates.push(`${duplicateId}/${watch.id}:${key}`);
      seen.set(key, watch.id);
    }

    expect(duplicates).toEqual([]);
  });

  it("keeps the D1 seed SQL generated from the JSON seed data", () => {
    expect(seedSql).toContain("-- Generated by npm run data:seed-sql. Do not edit by hand.");

    for (const watch of seed) {
      expect(seedSql).toContain(`(${watch.id}, ${sqlValue(watch.brand)}, ${sqlValue(watch.model)}`);

      for (const source of watch.sources) {
        expect(seedSql).toContain(`SELECT ${watch.id}, ${sqlValue(source.sourceUrl)}, ${sqlValue(source.note ?? null)}`);
      }
    }
  });

  it("requires a positive lug-to-lug value and at least one valid source URL", () => {
    for (const watch of seed) {
      expect(watch).not.toHaveProperty(["confi", "dence"].join(""));
      expect(watch.lugToLugMm).toBeGreaterThan(0);
      expect(watch.sources.length).toBeGreaterThan(0);

      for (const source of watch.sources) {
        expect(() => new URL(source.sourceUrl)).not.toThrow();
      }
    }
  });

  it("includes the planned Patek Philippe and Citizen expansion references without duplicates", () => {
    const referencesByBrand = (brand: string) =>
      seed.filter((watch) => watch.brand === brand).map((watch) => watch.reference);

    const patekReferences = referencesByBrand("Patek Philippe");
    const citizenReferences = referencesByBrand("Citizen");

    expect(patekReferences.length).toBeGreaterThanOrEqual(21);
    expect(new Set(patekReferences).size).toBe(patekReferences.length);
    expect(patekReferences).toEqual(
      expect.arrayContaining(["5811/1G-001", "5712/1A-001", "5167A-001", "5168G-010", "5821/1A-001"])
    );

    expect(citizenReferences.length).toBeGreaterThanOrEqual(27);
    expect(new Set(citizenReferences).size).toBe(citizenReferences.length);
    expect(citizenReferences).toEqual(
      expect.arrayContaining(["NB6021-17E", "NJ0180-80X", "NB6050-51W", "NJ0150-81L", "NJ0150-81Z"])
    );
  });

  it("includes the Grand Seiko expansion references without duplicates", () => {
    const grandSeikoReferences = seed.filter((watch) => watch.brand === "Grand Seiko").map((watch) => watch.reference);

    expect(grandSeikoReferences.length).toBeGreaterThanOrEqual(99);
    expect(new Set(grandSeikoReferences).size).toBe(grandSeikoReferences.length);
    expect(grandSeikoReferences).toEqual(
      expect.arrayContaining(["SBGN027", "SBGE285", "SBGW283", "SBGY013", "SLGB005", "SBGH376", "SBGX355"])
    );
  });

  it("returns planned expansion records through seed search", () => {
    for (const query of ["5712", "5167", "Promaster", "TSUYOSA", "Series8", "SBGN027", "SLGB005", "SBGX355"]) {
      expect(searchSeedWatches(query).length).toBeGreaterThan(0);
    }
  });

  it("returns Worn & Wound batch records through seed search", () => {
    for (const query of ["Deep Space Blue", "Crossroads S 36", "Inflection", "DW-5600MNC", "JetFlyer", "Grand Tonneau"]) {
      expect(searchSeedWatches(query).length).toBeGreaterThan(0);
    }
  });

  it("returns AV86 records through current, historical, and regional brand names", () => {
    const av86Records = seed.filter((watch) => watch.brand === "AV86");

    expect(av86Records).toHaveLength(41);
    for (const query of ["AV86", "About Vintage", "Skov Andersen"]) {
      expect(searchSeedWatches(query).filter((watch) => watch.brand === "AV86")).toHaveLength(41);
    }
    expect(seedSql).toContain("av86 about vintage skov andersen");
  });

  it("groups normalized variant-only seed families for display", () => {
    const expectedGroups = [
      ["omega-seamaster-diver-300m-42mm", [6, 7]],
      ["omega-speedmaster-moonwatch-professional-42mm", [2]],
      ["formex-reef-39-5mm-automatic-cosc-300m", [7]],
      ["traska-commuter-36", [3]],
      ["zelos-hammerhead-43-field", [7]],
      ["mido-multifort-tv-big-date-40mm", [4]],
      ["grand-seiko-sport-quartz-gmt-39mm", [2]],
      ["grand-seiko-elegance-manual-winding-37-3mm", [5]],
      ["grand-seiko-hand-winding-spring-drive-38-5mm", [4]],
      ["grand-seiko-evolution-9-spring-drive-5-days-40mm", [4]],
      ["grand-seiko-spring-drive-u-f-a-37mm", [4]],
      ["grand-seiko-62gs-mechanical-hi-beat-36000-38mm", [4]],
      // The two delugs-sourced colorways carry no thickness, so they display
      // as a second group next to the four fully-measured rows.
      ["fears-brunswick-40-5-jump-hour", [2, 4]],
      ["mido-multifort-tv-big-date", [6]],
      ["sternglas-naos-automatic-38mm-black", [2]],
      ["sternglas-naos-automatic-38mm-blue", [2]],
      ["sternglas-naos-automatic-38mm-white", [4]],
      ["breitling-chronomat-b01-42-nfl", [26]],
      ["swatch-moonswatch", [21]],
      ["christopher-ward-bel-canto-c1", [2, 19]],
      ["seiko-5-sports", [20]]
    ] as const;

    for (const [modelGroup, variantCounts] of expectedGroups) {
      const groups = groupWatchesForDisplay(seedWatches.filter((watch) => watch.modelGroup === modelGroup));
      const actualVariantCounts = groups.map((group) => group.variantCount).sort((a, b) => a - b);
      const expectedVariantCounts = [...variantCounts].sort((a, b) => a - b);

      expect(actualVariantCounts, modelGroup).toEqual(expectedVariantCounts);
    }
  });
});
