name = "lugtolug"
compatibility_date = "2026-05-16"
pages_build_output_dir = "dist"

[vars]
PUBLIC_SITE_URL = "https://lugtolugfinder.com"

[[d1_databases]]
binding = "DB"
database_name = "lugtolug-finder"
database_id = "f3244c7d-7c34-40ac-99c7-3663ec28d44a"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSION"
id = "dfacc8245c2940d9b8b982c797283af1"
