import brandSearchAliases from "../../data/brand-search-aliases.json" with { type: "json" };
import {
  buildWatchSearchText,
  getWatchSlugs,
  normalizeOptionalString
} from "../../src/lib/watchText.ts";

// These IDs must remain non-approved in D1 because they are superseded by
// stronger live product identities or were removed from the seed. Some still
// exist in the JSON fallback intentionally, so this is a D1 policy list rather
// than a list of IDs that must be absent from watches.seed.json.
export const D1_ARCHIVED_WATCH_IDS = [
  7, 14, 17, 18, 1462, 1463, 1464, 1468, 1469, 1933, 1972, 2001, 2002, 2761, 3100, 3105, 4463, 4477, 4486,
  6984, 7036, 7093, 7135, 7151, 7165, 7167, 7169, 7175, 7227, 7232, 7234, 7248, 7267, 7280, 7336, 7339,
  7353, 7371, 7404, 7427, 7430, 7448, 7450
];

export const WATCH_COLUMNS = [
  "id",
  "brand",
  "model",
  "canonical_model",
  "model_group",
  "variant",
  "reference",
  "brand_slug",
  "model_slug",
  "reference_slug",
  "search_text",
  "lug_to_lug_mm",
  "case_mm",
  "thickness_mm",
  "lug_width_mm",
  "status"
];

const WATCH_UPDATE_COLUMNS = WATCH_COLUMNS.filter((column) => !["id", "status"].includes(column));
const WATCH_INSERT_BATCH_SIZE = 100;

export function sqlValue(value) {
  if (value == null) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/gu, "''")}'`;
}

export function chunkValues(values, size) {
  return Array.from({ length: Math.ceil(values.length / size) }, (_, index) =>
    values.slice(index * size, (index + 1) * size)
  );
}

export function watchWithoutSources(watch) {
  const { sources: _sources, ...value } = watch;
  return value;
}

function watchSqlValues(watch) {
  const { brandSlug, modelSlug, referenceSlug } = getWatchSlugs(watch);

  return [
    watch.id,
    watch.brand,
    watch.model,
    normalizeOptionalString(watch.canonicalModel),
    normalizeOptionalString(watch.modelGroup),
    normalizeOptionalString(watch.variant),
    watch.reference,
    brandSlug,
    modelSlug,
    referenceSlug,
    buildWatchSearchText(watch, brandSearchAliases),
    watch.lugToLugMm,
    watch.caseMm,
    watch.thicknessMm,
    watch.lugWidthMm,
    "approved"
  ].map(sqlValue);
}

export function renderWatchUpsertStatement(watches) {
  if (watches.length === 0) throw new Error("Cannot render an empty watch upsert.");

  return [
    "INSERT INTO watches",
    `(${WATCH_COLUMNS.join(", ")})`,
    "VALUES",
    watches.map((watch) => `(${watchSqlValues(watch).join(", ")})`).join(",\n"),
    "ON CONFLICT(id) DO UPDATE SET",
    [
      ...WATCH_UPDATE_COLUMNS.map((column) => `  ${column} = excluded.${column}`),
      "  status = CASE WHEN watches.status = 'approved' THEN excluded.status ELSE watches.status END",
      "  updated_at = CURRENT_TIMESTAMP"
    ].join(",\n") + ";"
  ].join("\n");
}

export function renderSourceUpsertStatements({ watchId, sourceUrl, note = null }) {
  const watchIdSql = sqlValue(watchId);
  const sourceUrlSql = sqlValue(sourceUrl);
  const noteSql = sqlValue(note);

  return [
    `UPDATE watch_sources SET note = ${noteSql} WHERE watch_id = ${watchIdSql} AND source_url = ${sourceUrlSql};`,
    [
      "INSERT INTO watch_sources (watch_id, source_url, note)",
      `SELECT ${watchIdSql}, ${sourceUrlSql}, ${noteSql}`,
      `WHERE NOT EXISTS (SELECT 1 FROM watch_sources WHERE watch_id = ${watchIdSql} AND source_url = ${sourceUrlSql});`
    ].join("\n")
  ];
}

export function renderSeedSql(seed, { selectedBrand = null } = {}) {
  const scopedSeed = selectedBrand ? seed.filter((watch) => watch.brand === selectedBrand) : seed;
  if (scopedSeed.length === 0) {
    throw new Error(`No seed rows found${selectedBrand ? ` for brand ${selectedBrand}` : ""}.`);
  }

  const watchInsertStatements = chunkValues(scopedSeed, WATCH_INSERT_BATCH_SIZE).map(renderWatchUpsertStatement);
  const sourceStatements = scopedSeed.flatMap((watch) =>
    watch.sources.flatMap((source) =>
      renderSourceUpsertStatements({
        watchId: watch.id,
        sourceUrl: source.sourceUrl,
        note: source.note ?? null
      })
    )
  );

  return [
    selectedBrand
      ? `-- Generated by scripts/generate-seed-sql.mjs for brand: ${selectedBrand}. Do not edit by hand.`
      : "-- Generated by npm run data:seed-sql. Do not edit by hand.",
    "",
    ...(selectedBrand
      ? []
      : [
          "-- Superseded seed rows merged into canonical records.",
          `UPDATE watches SET status = 'archived', updated_at = CURRENT_TIMESTAMP WHERE id IN (${D1_ARCHIVED_WATCH_IDS.join(", ")}) AND status = 'approved';`,
          ""
        ]),
    "-- Deployed rows can still hold an older id layout; park their slugs on unique",
    "-- placeholders so the id-keyed upserts below cannot trip slug uniqueness mid-run.",
    `UPDATE watches SET reference_slug = 'seed-tmp-' || id WHERE id IN (${scopedSeed.map((watch) => watch.id).join(", ")});`,
    "",
    ...watchInsertStatements,
    "",
    "-- Idempotent source upserts keyed by watch_id and source_url.",
    ...sourceStatements,
    ""
  ].join("\n");
}
